## Copyright (c) 2011 The WebM project authors. All Rights Reserved.
## 
## Use of this source code is governed by a BSD-style license
## that can be found in the LICENSE file in the root of the source
## tree. An additional intellectual property rights grant can be found
## in the file PATENTS.  All contributing project authors may
## be found in the AUTHORS file in the root of the source tree.
# This file automatically generated by configure. Do not edit!
TOOLCHAIN := x86_64-linux-gcc
ALL_TARGETS += libs

PREFIX=/usr/local
ifeq ($(MAKECMDGOALS),dist)
DIST_DIR?=vpx-vp8-vp9-nodocs-x86_64-linux-Release
else
DIST_DIR?=$(DESTDIR)/usr/local
endif
LIBSUBDIR=lib

VERSION_STRING=Release

VERSION_MAJOR=Release
VERSION_MINOR=Release
VERSION_PATCH=Release

CONFIGURE_ARGS=--disable-unit-tests --disable-docs --disable-examples --enable-pic --enable-vp8 --enable-vp9 --enable-postproc --enable-vp9-postproc --enable-vp9-highbitdepth --enable-vp9-temporal-denoising --enable-multi-res-encoding --enable-webm-io --enable-libyuv --extra-cflags=-fvisibility=hidden
CONFIGURE_ARGS?=--disable-unit-tests --disable-docs --disable-examples --enable-pic --enable-vp8 --enable-vp9 --enable-postproc --enable-vp9-postproc --enable-vp9-highbitdepth --enable-vp9-temporal-denoising --enable-multi-res-encoding --enable-webm-io --enable-libyuv --extra-cflags=-fvisibility=hidden
